### PR TITLE
Feature#6 home layout

### LINKED ISSUE #6: HomePageLayout
# REQUIREMENTS
Welcome Message
Current Date
Reminder notes section
Fav notes section

# DESIGN

image

### PR DESCRIPTION
**Pull request by Jonathanrrs**
# Description

- We add tab navigation
- We add drawer navigation
- We add the greeting to the user and the switch to change the dark mode
- We add the cards for the reminders that exist on the current day
- We added the cards for only 5 notes with I love it

  ## Screenshots 
image

image

### CODE REVIEW

**Review by VaninaWinnik — DISMISSED** [review]

**Review by Kejoh — DISMISSED** [review]
GW! I like your side menu

**Review by osvilla27 — DISMISSED** [review]

**Review by w01fgxng — DISMISSED** [review]
Good Job! the Color Pallet was awesome!

**Review by VaninaWinnik — APPROVED** [review]

**Review by osvilla27 — APPROVED** [review]

**Review by w01fgxng — APPROVED** [review]
Good Job!

**Review by Kejoh — APPROVED** [review]
Good job!

**Pull request merged**
