### PR TITLE
reminders in home page

### LINKED ISSUE #25: RemindersHomePage
# REQUIREMENTS
If the user has reminders for the current day they will be shown, if not a message will be shown indicating this.

Story points 2

### PR DESCRIPTION
**Pull request by Jonathanrrs**
# Description

- In case there are no reminders for the current day a message is displayed.
- Added a message to show that it is the end of the reminder list.
- A loading with animation was added when the reminders load.

  
  ## Screenshots 
image

### CODE REVIEW

**Review by Kejoh — DISMISSED** [review]

**Review by w01fgxng — APPROVED** [review]
gw

**Review by w01fgxng — DISMISSED** [review]
x2

**Review by osvilla27 — DISMISSED** [review]
Great...

**Review by VaninaWinnik — DISMISSED** [review]

**Review by w01fgxng — APPROVED** [review]
GREAT WORK!

**Review by jbernalme — APPROVED** [review]

**Review by w01fgxng — APPROVED** [review]

**Review by Kejoh — APPROVED** [review]
Fantastic logo

**Review by osvilla27 — APPROVED** [review]
Great job

**Pull request merged**
