### PR TITLE
Feature#3 user auth layout

### LINKED ISSUE #3: User authentication layout
# REQUIREMENTS
Layout authentication pages.

- Fields for name, email and password in the registration
- Fields for name and password in the login
- Google login buttons

# DESIGN
image

### PR DESCRIPTION
**Pull request by Jonathanrrs**
# Description
 - We create the user registration screen with its fields
 - We create the user login screen with its fields.

  
  ## Screenshots 
image
image

### CODE REVIEW

**Review by w01fgxng — DISMISSED** [review]
GJ!

**Review by Kejoh — DISMISSED** [review]

**Review by Kejoh — APPROVED** [review]

**Review by osvilla27 — APPROVED** [review]
Cool...

**Review by Kejoh — APPROVED** [review]
Good work

**Review by Etneciv — APPROVED** [review]
Good job with design

**Pull request merged**
